### ISSUE TITLE
Case number 15 information validity

### ISSUE THREAD

**Issue by valstu** [HS-Datadesk/koronavirus-avoindata#16]
I got some feedback that according to some news sources case number 15 would be originally from Iran not Italy. At least these sources are claiming so (sorry articles are in Finnish):
- https://yle.fi/uutiset/3-11244714

And these two articles are using Yle as a source:
- https://www.kaleva.fi/uutiset/pohjois-suomi/pohjois-pohjanmaalla-todettu-ensimmainen-koronavirustartunta-suomessa-nyt-yhteensa-15-koronatapausta/836360/
- https://www.keskipohjanmaa.fi/uutinen/590544

**Comment by quarian** [comment]
I don't doubt YLE - the initial source country labelling was done blanket-wise, and when it was done most cases were from Italy and this data point was mislabeled either by accident or lacking better information.

Anyhow, the data is now updated to reflect YLE's information.
