### ISSUE TITLE
Itävalta merkitty virheellisesti AUS-maakoodilla

### ISSUE THREAD

**Issue by jukkapaananen** [HS-Datadesk/koronavirus-avoindata#17]
Itävallan pitäisi olla AUT, Australia on AUS.
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by quarian** [comment]
Juuri puhuttiin tästä. Korjataan.

**Comment by quarian** [comment]
Korjattu. @jukkapaananen

**Comment by valstu** [comment]
Onko nuo caset 159, 160, 239 ja 267 peräisin Australiasta vai merkkausvirhe?
