### ISSUE TITLE
Case with id 60 missing

### ISSUE THREAD

**Issue by valstu** [HS-Datadesk/koronavirus-avoindata#18]
Case id should be running number starting from 1 but it seems like case with id 60 is missing.

**Comment by quarian** [comment]
Yes, manual data input error. I wonder if fixing that would break someone's system? If for example someone having the id as their database primary key changing those might cause issues. Personally I don't think that's such big deal - if you wanted the amount of cases, you should anyway to use the length of the array. Thoughts @valstu ?

**Comment by valstu** [comment]
Ok, makes sense, I initially thought there's something wrong with the data because I saw id 87 and there was only 86 confirmed cases :)  But yeah I agree, it might break stuff on some systems, so lets keep the way it is.
