### ISSUE TITLE
Case number 60 is missing

### ISSUE THREAD

**Issue by petterw03** [HS-Datadesk/koronavirus-avoindata#19]
I just noticed that the confirmed array only has 86 objects, even though there should be 87 cases. Case number 60 seems to be missing.

**Comment by quarian** [comment]
Yeah, this was a data input error. Discussed also here: https://github.com/HS-Datadesk/koronavirus-avoindata/issues/18.

TL;DR - no data error, and I believe fixing the id is more trouble than it's worth. So let's keep things as they are. @petterw03
