### ISSUE TITLE
Timestamps in the future

### ISSUE THREAD

**Issue by jonniek** [HS-Datadesk/koronavirus-avoindata#20]
I need a sanity check. If I'm not mistaken the UTC time as of writing this issue is 10:52 but the api returns `id: 87, date: "2020-03-12T11:15:00.000Z"`.

**Comment by quarian** [comment]
This was Yet Another Adventure to Timezone Land `TM`. I have now added correct date setting to the lambda and your sanity should be restored. For those curious, this was the reason for this issue:

1) We store data in the format `YYYY-MM-DDTHH:MM` (for easier manual entry), and this contains no time zone data. So when people enter data it's implicitly the timezone is Eastern European Time (EET).

2) The lambda that serves the data lives in Ireland, in UTC. So the times were coerced to UTC in the Lambda (with JS `new Date()`). So this caused the time jump perceived here.

3) I added EET information to the Lambda time handling, so the data coming out should be fine now.

Closing, @jonniek . Thanks for the bug note!
