### ISSUE TITLE
Case 110 infectionSourceCountry value

### ISSUE THREAD

**Issue by valstu** [HS-Datadesk/koronavirus-avoindata#22]
Case 110 `infectionSourceCountry` seems to be empty string `""` at the moment. On other cases where there isn't `infectionSourceCountry` the value is `null`

**Comment by quarian** [comment]
Hmm, interesting. Visually in our data editor  there's nothing. Let me inspect.

**Comment by quarian** [comment]
Should be uniform now - close issue if you agree @valstu

**Comment by valstu** [comment]
Seems to be fine now, thanks for your prompt reply! Closing issue.

**Comment by petterw03** [comment]
There is also the same problem with case 218.
