### ISSUE TITLE
Infection dates question

### ISSUE THREAD

**Issue by valstu** [HS-Datadesk/koronavirus-avoindata#23]
I've gotten few questions about the dates of the cases today. Many sources have been talking about 50 new infections today but the dataset says that today (12.3.) there has been 44 cases. Although the total number of confirmed infections match with the data from THL.  https://thl.fi/fi/-/suomessa-on-todettu-50-uutta-koronavirustartuntaa-?redirect=%2Ffi%2F

Is this because the accurate date of the infection is not known? Or is THL just calculating daily cases based on office hours? :) eg. from 6am to 6am?

**Comment by valstu** [comment]
Also could be that THL probably ends their day at 16:00 - 17:00 and every infection after that is added to the next day? 🤔

**Comment by valstu** [comment]
Oh, and there are two new cases now so my example numbers doesn't match anymore

**Comment by quarian** [comment]
As far as I can piece together:

1) We note incidents when they come to our attention - for example the two cases today happened after the THL notice this morning. Most likely those will be in the combined information from THL tomorrow, throwing the "daily" infections a little out of sync.
2) There is chance of human error in the marking of dates, though I'm fairly confident that the dates currently are about right.

Also, the date we tell is the date of observation by us, not necessarily the date when the infection was reported originally or the time the infection was diagnosed, for example.

The goal is to keep the overall amount correct and the dates as close to correct as possible. The information sources are fragmented (when they don't come from THL), so it might even take a little time to verify the correctness of information, which might cause lags as well.

Does this answer your questions thoroughly enough?

**Comment by valstu** [comment]
This answered my questions really thoroughly, thank you!
