### ISSUE TITLE
Case 163 only has 2-character country code

### ISSUE THREAD

**Issue by lakaniemi** [HS-Datadesk/koronavirus-avoindata#28]
Case 163 looks like this now:
```
{
    id: "163",
    date: "2020-03-14T08:48:00.000Z",
    healthCareDistrict: "Pirkanmaa",
    infectionSourceCountry: "CH",
    infectionSource: "unknown"
},
```

Maybe this is typo, and is meant to say CHN? `CH` is alpha-2 code for Switzerland though, so it's a bit confusing now :D

**Comment by quarian** [comment]
Should be a typo - and has been fixed now. Thanks for noticing @lakaniemi ! I'll double check the info and update it if necessary later - it should definitely be a three character code.
