### ISSUE TITLE
Add "international" as a possible source?

### ISSUE THREAD

**Issue by tuukka** [HS-Datadesk/koronavirus-avoindata#3]
Currently, most cases are listed as "infectionSource: unknown", but could they be listed as "infectionSource: international" or even specify the country? I would like to separate everyday life from international cases.

In this sense, none of the cases in Finland are unknown: "Tähän mennessä Suomessa on todettu 30 laboratoriovarmistettua uuden koronaviruksen (COVID-19) aiheuttamaa tautitapausta. Niistä 23 liittyy matkailuun ja jatkotartuntoja on seitsemän." https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/ajankohtaista/ajankohtaista-koronaviruksesta-covid-19

**Comment by quarian** [comment]
A reasonable request - we'll add the geographical information to the data. Let's keep the `infectionSource`as is (so it pinpoints a person if it can). I'll add `sourceCountry` or something for the geographical data.

**Comment by EsaMakinen** [comment]
Master data has been updated to reflect this change.

**Comment by EsaMakinen** [comment]
Solved in: https://github.com/HS-Datadesk/koronavirus-avoindata/pull/4

**Comment by tuukka** [comment]
Thanks guys - that was quick!
