### ISSUE TITLE
Consistent "id" types for recovered objects 

### ISSUE THREAD

**Issue by lovelldies** [HS-Datadesk/koronavirus-avoindata#31]
![image](https://user-images.githubusercontent.com/7194108/76704788-0de66100-66e4-11ea-8ab0-6e432b45b09a.png)

The values for id 1 and 2 are numeric, whereas 3 onwards are strings. Could you update this so that all are of the same type? I guess all id should be sent as string.

Related to that, the [documentation](https://github.com/HS-Datadesk/koronavirus-avoindata#data-format) says that the IDs should be numeric, but the API sends them as string.

**Comment by quarian** [comment]
Huh, thanks for noticing! The docs should be fixed in https://github.com/HS-Datadesk/koronavirus-avoindata/pull/32, and the data should be now formatted correctly. If you agree, let's close this issue.

@lovelldies

**Comment by lovelldies** [comment]
Thanks @quarian!
