### ISSUE TITLE
Myös kriittiset tapaukset mukaan dataan

### ISSUE THREAD

**Issue by miikkajs** [HS-Datadesk/koronavirus-avoindata#34]
Esim. ``"critical": [
 {
      "id": "1",
      "date": "2020-03-16T11:00:00.000Z",
      "healthCareDistrict": "HUS"
    }
]``

**Comment by quarian** [comment]
Olisi mielenkiintoista - meillä on just taustalla käynnissä kartoitus miten tommosta (ja muuta) dataa sais luotettavasti kerättyä. Ilmoittelemme kun on jotain uutta kerrottavaa. Jätän tämän auki keskustelua varten jos tulee muille ideoita.

**Comment by Karvaporsas** [comment]
Voisiko olla niin, että confirmedin alkioilla olisi parametri "severity"?

**Comment by petterw03** [comment]
THL:n sivulla löytyy nyt tätä dataa: https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/ajankohtaista/ajankohtaista-koronaviruksesta-covid-19/tilannekatsaus-koronaviruksesta

**Comment by quarian** [comment]
Nyt olis: https://github.com/HS-Datadesk/koronavirus-avoindata/pull/55

**Comment by quarian** [comment]
@Karvaporsas @miikkajs @petterw03
