### ISSUE TITLE
healthCareDistrict is null since 2020-3-18 

### ISSUE THREAD

**Issue by Marantle** [HS-Datadesk/koronavirus-avoindata#40]
Hi, noticed that since today the healthCareDistrict field is displaying null for all new infections, starting with this one
```
    {
      "id": "345",
      "date": "2020-03-18T15:10:00.000Z",
      "healthCareDistrict": null,
      "infectionSourceCountry": null,
      "infectionSource": "unknown"
    }
```

this is a bummer for apps such as mine which utilizes this data

**Comment by quarian** [comment]
Yeah sorry, I had to do this patch yesterday in a hurry and didn't have time to add anything here. The reason for this is that THL no longer reports the districts on all the reported infections - so we don't know it. It being `null` is correct - I'll add it to the docs. For the items we can, we put the district, but going forward there will be things with `null`s unfortunately. @Marantle

**Comment by quarian** [comment]
Added a note to the docs in https://github.com/HS-Datadesk/koronavirus-avoindata/pull/42

**Comment by Marantle** [comment]
Ok, its sad but cant be helped then, thanks for the reply
