### ISSUE TITLE
Sairaanhoitopiiri NULL

### ISSUE THREAD

**Issue by Karvaporsas** [HS-Datadesk/koronavirus-avoindata#43]
Useissa vahvistetuissa tapauksissa healthCareDistrict on null jostain syystä. Onko tämä tarkoituksenmukaista vai virhe?

**Comment by maeehart** [comment]
Tätä minäkin ihmettelen. Tämän datan tärkein syy oli varmaan tutkia tapauksien sijanintia, joten olisi tärkeää saada se sairaanhoitopiiri sinne!

**Comment by Marantle** [comment]
Tästä samasta asiasta ilmoitin jo eilen ja sain vastauksen -> https://github.com/HS-Datadesk/koronavirus-avoindata/issues/40
Ehkä hieman hätiköiden suljin issuen  kun varmasti en ollut ainoa ketä asiaa ihmetteli

**Comment by quarian** [comment]
Jees, eli kuten yllä. THL säätää omia systeemeitään - katotaan jahka sieltä tulee jotain infoa tosta niiden kantaan suoraan pääsystä. https://thl.fi/fi/-/thl-alkaa-kerata-tiedot-koronatartunnoista-tartuntatautirekisterista-tahan-mennessa-tiedot-on-koostettu-kasin

**Comment by quarian** [comment]
Myös, kollega kirjoittaa: https://www.hs.fi/politiikka/art-2000006445897.html

**Comment by Karvaporsas** [comment]
Mjoop. Tämän voi varman merkata duplikaatiksi labelilla. Suljen tiketin.

**Comment by petterw03** [comment]
7 out of the null sairanhoitopiirit should be from Vaasa. 

Is there any way to crowdsource the collection of this data straight from the hoitopiirit?

**Comment by quarian** [comment]
I wouldn't attempt that now - the officials are trying to set up a system that wouldn't require prodding the already busy healthcare professionals. I'd suggest we give them a little time. @petterw03 do you have a source to the Vaasa information? I can update the data if the source is official.

**Comment by petterw03** [comment]
https://yle.fi/uutiset/3-11265545
