### ISSUE TITLE
Duplikaatti-id:t

### ISSUE THREAD

**Issue by tuomasgu** [HS-Datadesk/koronavirus-avoindata#45]
Confirmed-joukkoon tulee id 410:n tiedot kahteen kertaan. Tämä on duplikaatti tällä hetkellä. Onkohan juokseva numerointi pysähtynyt vai tieto päivittynyt ja vanha jäänyt jäljelle? Onko tälle jokin tulkinta?

```
{'id': '410',
  'date': '2020-03-19T12:25:00.000Z',
  'healthCareDistrict': None,
  'infectionSourceCountry': None,
  'infectionSource': 'unknown'},
 {'id': '410',
  'date': '2020-03-20T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': None,
  'infectionSource': 'unknown'}
```

**Comment by quarian** [comment]
Oltiin typotettu id 401 410:ksi, nyt korjattu. Sulje jos samaa mieltä @tuomasgu

**Comment by tuomasgu** [comment]
Hyvä, kiitos! Tuo selittää. Voidaan sulkea.
