### ISSUE TITLE
Keski-suomen tartunnat null

### ISSUE THREAD

**Issue by maeehart** [HS-Datadesk/koronavirus-avoindata#47]
... vaikka löytyvät osoitteesta https://www.ksshp.fi/fi-FI/Potilaalle/Koronatiedotus/Koronavirus_lukuina__Coronavirus_in_numb(60094)

**Comment by quarian** [comment]
Voitko selittää tarkemmin - minusta näyttää, että rajapinta palauttaa oikean määrän Keski-Suomen tartuntoja (23). @maeehart

**Comment by maeehart** [comment]
Nyt se onkin jo kunnossa. Oli ehditty näköjään korjata välissä ennen kuin sain kirjoitetua issuen. Suljen.
