### ISSUE TITLE
healthCareDistrict joko "" tai null ero?

### ISSUE THREAD

**Issue by villesau** [HS-Datadesk/koronavirus-avoindata#48]
Hei,

näyttää siltä, että healthCareDistrict voi olla joko sairaanhoitopiiri, null tai tyhjä stringi. Mikä ero on nullilla ja tyhjällä stringillä?

**Comment by quarian** [comment]
Lienee bugi lähdedatan muuttamisessa JSONiksi. Ei pitäisi olla eroa - käyn tarkistamssa kohta mistä on kysymys.

**Comment by quarian** [comment]
@villesau nyt pitäis olla OK tämän.

**Comment by lovelldies** [comment]
@quarian following up on this thread, is `null` in `healthCareDistrict: null` a valid value for and unknown/confidential health care district?

**Comment by quarian** [comment]
@lovelldies it is, currently THL doesn't tell the health care districts of the cases (we piece information from other sources when we have time, but it's not efficient or a good use of time). That should improve at some point, THL is supposedly working on releasing their own data directly. But for now this is how it is. The closest interpretation is "Health care district non announced".

**Comment by lovelldies** [comment]
@quarian thanks for the clarification.
