### ISSUE TITLE
Montako testattu missäkin sairaanhoitopiirissä?

### ISSUE THREAD

**Issue by villesau** [HS-Datadesk/koronavirus-avoindata#49]
Olisi hyvä saada data myös testattujen määristä sairaanhoitopiireittäin. Onkohan tälläistä dataa saatavilla?

**Comment by quarian** [comment]
Sairaanhoitopiirit itse ilmoittavat testattujen määriä, mutta tieto on hajallaan ja ei läheskään kaikista sairaanhoitopiireistä. En usko että juuri nyt on järkeä alkaa rakentaa sille putkea - THL:n pitäisi tässä kohtisillään laittaa ulos rajapinta suoraan heidän datoihinsta, jonka jälkeen voidaan miettiä jos halutaan sitä lähteä rikastamaan jollain.

**Comment by villesau** [comment]
Tämän artikkelin mukaan testattujen määrä voisi ola yhteiskunnallisestikin arvokasta tietoa: https://www.hs.fi/kotimaa/art-2000006457838.html

> HUSIN toimitusjohtaja Juha Tuominen ei ole yhtä toiveikas nopean muutoksen suhteen.

> ”Olisin maltillinen tekemään johtopäätöksiä yksittäisten päivien perusteella. Luvut täytyy suhteuttaa mittausmäärään. Se voi vaihdella päivittäin”, Tuominen sanoo HS:lle.

**Comment by EsaMakinen** [comment]
Tämä on työn alla

**Comment by quarian** [comment]
Datan käsittely on kirjoitettu, mutta nyt on liian perjantai-ilta avata dataa. Tulossa.

**Comment by quarian** [comment]
Hetki meni, mutta tässä olisi https://github.com/HS-Datadesk/koronavirus-avoindata/pull/73.

@villesau
