### ISSUE TITLE
Add data on cases requiring intensive care (tehohoito)

### ISSUE THREAD

**Issue by ahatala** [HS-Datadesk/koronavirus-avoindata#52]
HS publishes the number of patients requiring intensive care daily, being able to track these would be highly valuable as the number is less dependent on testing capacity and criteria.

**Comment by quarian** [comment]
We have that internally, but since it's 20:16 on a Friday I'm not going to update the API right now. Also, the future of this API is under consideration, since THL has activated and published their numbers (https://github.com/HS-Datadesk/koronavirus-avoindata/pull/53). I'll get back to this.

**Comment by quarian** [comment]
Is added now, see https://github.com/HS-Datadesk/koronavirus-avoindata/pull/55. @ahatala 

I'll be closing this issue and the other one soon and start discussion on maybe how to improve the endpoint I now made.
