### ISSUE TITLE
v2 API frequent 502 Bad Gateway

### ISSUE THREAD

**Issue by jonniek** [HS-Datadesk/koronavirus-avoindata#61]
About every fifth request fails for me. This never happened with v1 API.

Log: https://hastebin.com/efedusewel.json

Perhaps interesting part of log header `x-amzn-errortype: InternalServerErrorException`

**Comment by quarian** [comment]
Thanks for the info - I'll investigate.

**Comment by quarian** [comment]
Right, so I found at least one bug that could cause this. The old API uses just database to serve the results, whereas this new one pulls from three distinct ones (THL and two of our own). I have parallelised the queries for performance, but there was a deadlocking execution path. It has been fixed now - let's monitor if this fixes the errors. @jonniek

**Comment by quarian** [comment]
Logs show a drop of 5XX errors back to 0 - what's the feel on the consumer side?

**Comment by jonniek** [comment]
Works well now
