### ISSUE TITLE
Broken links to the JSON examples

### ISSUE THREAD

**Issue by lovelldies** [HS-Datadesk/koronavirus-avoindata#62]
It seems like links to the example json files are not updated in the README file.

If you check: https://github.com/HS-Datadesk/koronavirus-avoindata#updating-interfaces
The first example links is wrong. I think the Finnish link might also be broken.

**Comment by quarian** [comment]
Thanks for noticing, I'll investigate.

**Comment by quarian** [comment]
You are correct, I'll fix them (but probably tomorrow, since not a pressing issue)

**Comment by quarian** [comment]
Fixed in https://github.com/HS-Datadesk/koronavirus-avoindata/pull/64.
