### ISSUE TITLE
Recovered count in "v2" endpoint is not updated

### ISSUE THREAD

**Issue by lovelldies** [HS-Datadesk/koronavirus-avoindata#71]
https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaData/v2

The **recovered** cases don't seem to be updated. Is this as designed?

**Comment by quarian** [comment]
No, since the recovered data hasn't been considered to be of that good quality. It's true that Johns Hopkins reports 300 recovered in Finland, but we have yet to be able to verify where that number comes from. Would you happen to know by chance?

**Comment by lovelldies** [comment]
Oh alright. I was seeing a lot of new floating around about 300 recovered cases and thought it was true.

Anyway thank for the clarification. Even Yle hasn't "confirmed" the number, so you are correct.
