### ISSUE TITLE
Rokotusdata ei päivittynyt 3.2. jälkeen

### ISSUE THREAD

**Issue by Karvaporsas** [HS-Datadesk/koronavirus-avoindata#84]
Rokotusdata ei vaikuta päivittyneen 3.2. jälkeen. Onko rajapinta poistunut käytöstä, viallinen vai onko THL:llä vaikeuksia saada lukuja? :)

**Comment by quarian** [comment]
Tuo rokotusdata tuli alun perin meidän käsin keräämästämme, mutta vaihdettiin viime viikolla THL:ltä automaattisesti kerättävään dataan. Avoimen datan rajapinnat ovat vielä päivittämättä, mutta tänään on tarkoitus se tehdä.

**Comment by quarian** [comment]
@Karvaporsas nyt pitäisi olla automaattisesti päivittyvät datat - formaatin pitäis olla myös sama olettaen että en kirjoitellut mitä sattuu.

**Comment by Karvaporsas** [comment]
Vaikuuttaisi toimivan. Nice!
