### ISSUE TITLE
Coronadata palauttaa Internal Server Error

### ISSUE THREAD

**Issue by Karvaporsas** [HS-Datadesk/koronavirus-avoindata#85]
Rajapinta

https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaData/v2

palauttaa virhettä kutsuttaessa.

**Comment by quarian** [comment]
Jaahas, näyttää että ollaan taas Lambdan kantokyvyn rajoilla. Katotaas.

**Comment by quarian** [comment]
Voin tod näk paikata väliaikaisesti muuttamalla noiden id:iden luomistapaa (jotta datan määrä vähenee), mutta tämä endpoint alkaa olla lambda-tiensä päässä. Hajoaakohan ihmisten systeemit jos muutan noiden tartuntojen id:itä?

Taustalla siis se että lambdalla joka ton datan parsii ja jakaa on 6 megan raja (AWS:n rajoitus) siinä mitä se pystyy läpi puskemaan ja sen rajan yli on nyt tässä menty.

**Comment by Karvaporsas** [comment]
Todennäköisesti hajoaa.

Mitä jos rajapinta tarjoaisi sairaanhoitopiireittäin datan finnishCoronaData/v2/HUS jne

Tai ottaisi parametrina montako päivää taaksepäin palautetaan dataa?

**Comment by quarian** [comment]
Mahdollista. Ei toki auta suoraan niitä jotka on jo integroitunu tohon rajapintaan.

Periaatteessa olisi kaikkien paras käyttää noita paremmin muotoiltuja rajapintoja:

Tartunnat: https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/processedThlData
Sairaala + kuolemat: https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaHospitalData

Katotaan mitä tälle tehdään, olen nyt kiinni muissa töissä mutta palaan asiaan.

**Comment by quarian** [comment]
@Karvaporsas katoppas josko toimisi. Siirsin sisällön paketoinnin lambdan sisään (sen sijaan että se gzipattaisiin API GW:ssä).

**Comment by Karvaporsas** [comment]
Lukeminen onnistui. Kiitoksia. :)
