### ISSUE TITLE
Sairaaladata ei ole päivittynyt 23.6.2021 jälkeen

### ISSUE THREAD

**Issue by baobabKoodaa** [HS-Datadesk/koronavirus-avoindata#87]
Tätä kirjoittaessa viimeisin entry sairaaladatassa on 2021-06-23T11:41:00.000Z. Onko tietoa mikä tämän datan tilanne on?

**Comment by quarian** [comment]
Jeps, tämä on tiedossa. Taustaa:

THL päivitti sairaala- ja kuolematiedot tuohon päivämäärään asti sivuilleen taulukkona päivittäin josta me ne raavittiin. Sitten lopettivat ja nyt tiedon saa vain THL:n rajapinnoista.

En ole vielä ehtinyt päivittää avoimen datan rajapintoja, mutta se on TODO-listalla. Pistän kommenttia tänne kun kerkeän päivittää.

En vielä ole keksinyt mikä on tyylikkäin tapa tehdä tämä, sillä meidän keräämässämme datassa on dataa pidemmältä ajalta kuin mitä THL:n rajapinnasta saa, joten mistä kohtaa katkaistaan ja yhdistellään tietoa on vielä päättämättä.

FYI @baobabKoodaa

**Comment by quarian** [comment]
@baobabKoodaa nyt on yks versio korjauksista livenä.

https://github.com/HS-Datadesk/koronavirus-avoindata/pull/88

**Comment by baobabKoodaa** [comment]
Kiitos Miro!

**Comment by quarian** [comment]
Jeps, jatketaan pelejä, suljen tän.
